version: "3.8"

services:
  app:
    restart: always
    entrypoint: wait-for db:5432 -- wait-for -t 120 kafka:29092 -- docker/entrypoint.sh
    volumes:
      - ./:/app

  db:
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:cached
    ports:
      - "15432:5432"

  kafka:
    image: "confluentinc/cp-kafka:latest"
    ports:
      - "29094:29094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,OUTSIDE://0.0.0.0:29094"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,OUTSIDE://localhost:29094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
    restart: unless-stopped
#    logging:
#      driver: "none"

  zookeeper:
    image: "confluentinc/cp-zookeeper"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    logging:
      driver: "none"

  schema-registry:
    image: "confluentinc/cp-schema-registry"
    hostname: "localhost"
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
    logging:
      driver: "none"
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:8081/subjects" ]
      interval: 5s
      timeout: 5s
      retries: 15
    environment:
      SCHEMA_REGISTRY_DEBUG: "true"
      SCHEMA_REGISTRY_HOST_NAME: "localhost"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "PLAINTEXT"
      SCHEMA_REGISTRY_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      SCHEMA_REGISTRY_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      SCHEMA_REGISTRY_STATUS_STORAGE_REPLICATION_FACTOR: "1"

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.0.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  kafka-worker:
    entrypoint: wait-for db:5432 -- wait-for -t 120 kafka:29092 -- wait-for -t 120 schema-registry:8081 -- docker/entrypoint.sh
