"""author default id

Revision ID: 2553394d1d6c
Revises: 00bfac279db0
Create Date: 2022-03-07 15:16:04.820216
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2553394d1d6c"
down_revision = "00bfac279db0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
