"""author

Revision ID: 00bfac279db0
Revises: 78924b0aa72f
Create Date: 2022-03-05 18:44:21.577569
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "00bfac279db0"
down_revision = "78924b0aa72f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("book", sa.Column("author_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, "book", "author", ["author_id"], ["id"])
    op.drop_column("book", "author")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("author", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "book", type_="foreignkey")
    op.drop_column("book", "author_id")
    op.drop_table("author")
    # ### end Alembic commands ###
