"""init

Revision ID: 2bc1046f14a7
Revises:
Create Date: 2022-01-19 08:51:45.877083
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bc1046f14a7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
