"""book

Revision ID: 78924b0aa72f
Revises: 2bc1046f14a7
Create Date: 2022-01-20 09:01:08.444229
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78924b0aa72f"
down_revision = "2bc1046f14a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book")
    # ### end Alembic commands ###
